import { CommonModule, DatePipe } from '@angular/common';
import { Component, computed, effect, HostListener, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from './api.service';
import { AuthService } from './auth.service';
import { ExtractedProduct, Product } from './models';

@Component({ selector: 'app-root', imports: [CommonModule, FormsModule, DatePipe], styleUrl: './app.css', templateUrl: './app.html' })
export class App {
  private api = inject(ApiService);
  private auth = inject(AuthService);
  constructor() { void this.auth.initialize(); }
  readonly products = signal<Product[]>([]); readonly view = signal<'active' | 'archived'>('active'); readonly selectedFile = signal<File | null>(null); readonly previewUrl = signal<string | null>(null); readonly extracted = signal<ExtractedProduct | null>(null); readonly replacingId = signal<string | null>(null); readonly captureDialogOpen = signal(false); readonly processing = signal(false); readonly saving = signal(false); readonly message = signal('Inicia sesión y añade una foto para crear tu inventario.'); readonly loginEmail = signal(''); readonly loginPassword = signal(''); readonly passwordVisible = signal(false); readonly loginLoading = signal(false); readonly loginError = signal(''); readonly logoutDialogOpen = signal(false); readonly logoutLoading = signal(false); readonly connected = signal(false);
  readonly daysToday = computed(() => this.products().filter(p => this.daysUntil(p.expiration_date) === 0).length); readonly daysSoon = computed(() => this.products().filter(p => { const d = this.daysUntil(p.expiration_date); return d > 0 && d <= 5; }).length); readonly total = computed(() => this.products().length);
  readonly userEmail = computed(() => this.auth.email());
  private syncAuth = effect(() => { const session = this.auth.session(); if (session && !this.connected()) { this.connected.set(true); this.loginError.set(''); this.message.set('Tu despensa está sincronizada.'); this.loadProducts(); } else if (!session && this.connected()) { this.connected.set(false); this.products.set([]); this.view.set('active'); this.message.set('Sesión cerrada. Tus productos permanecen protegidos.'); } });
  async loadProducts() { if (!this.connected()) return; try { this.products.set(await this.api.listProducts(this.view() === 'archived')); } catch { this.message.set('No se han podido cargar los productos. Comprueba tu conexión y sesión.'); } }
  onFile(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; if (!file.type.startsWith('image/')) { this.message.set('Selecciona una imagen JPG, PNG o WebP.'); return; } if (file.size > 5 * 1024 * 1024) { this.message.set('La imagen no puede superar 5 MB.'); return; } this.selectedFile.set(file); this.previewUrl.set(URL.createObjectURL(file)); this.extracted.set(null); this.message.set('Imagen lista. Analízala para comprobar la fecha antes de guardar.'); }
  async analyze() { const file = this.selectedFile(); if (!file) return; if (!this.connected()) { this.message.set('Inicia sesión antes de analizar y guardar una foto.'); return; } this.processing.set(true); try { const result = await this.api.analyzePhoto(file, this.replacingId() || undefined); this.extracted.set(result); this.message.set('Información encontrada. Revísala antes de confirmar.'); if (this.replacingId()) { await this.loadProducts(); this.resetCapture(); this.captureDialogOpen.set(false); } } catch { this.message.set('No se ha podido leer la foto. Asegúrate de que la fecha se ve con nitidez.'); } finally { this.processing.set(false); } }
  async save() { const item = this.extracted(); if (!item) return; if (!this.connected()) { this.message.set('Inicia sesión antes de guardar productos.'); return; } if (!item.source_image_path) { this.message.set('Falta la foto original; vuelve a analizarla antes de guardar.'); return; } this.saving.set(true); try { const saved = await this.api.saveProduct(item); this.products.update(items => [saved, ...items]); this.message.set('Producto guardado. Te avisaremos antes de que caduque.'); this.resetCapture(); this.captureDialogOpen.set(false); } catch { this.message.set('No se ha podido guardar el producto. Inténtalo de nuevo.'); } finally { this.saving.set(false); } }
  async consume(product: Product) { if (!this.connected()) { this.message.set('Inicia sesión antes de archivar productos.'); return; } try { await this.api.consume(product.id); this.products.update(items => items.filter(item => item.id !== product.id)); this.message.set(`${product.name} se ha archivado como gastado.`); } catch { this.message.set('No se ha podido archivar el producto.'); } }
  openCaptureDialog() { this.resetCapture(); this.captureDialogOpen.set(true); window.setTimeout(() => document.getElementById('capture-close')?.focus()); }
  closeCaptureDialog() { if (this.processing() || this.saving()) return; this.resetCapture(); this.captureDialogOpen.set(false); window.setTimeout(() => document.getElementById('capture-trigger')?.focus()); }
  replace(product: Product) { this.replacingId.set(product.id); this.selectedFile.set(null); this.previewUrl.set(null); this.extracted.set(null); this.captureDialogOpen.set(true); window.setTimeout(() => document.getElementById('capture-close')?.focus()); this.message.set(`Sube una nueva foto para actualizar la fecha de ${product.name}.`); }
  setView(view: 'active' | 'archived') { this.view.set(view); this.loadProducts(); }
  daysUntil(date: string) { const today = new Date(); today.setHours(0,0,0,0); return Math.round((new Date(`${date}T00:00:00`).getTime() - today.getTime()) / 86400000); }
  urgency(product: Product) { const days = this.daysUntil(product.expiration_date); if (days <= 0) return 'today'; if (days === 1) return 'tomorrow'; if (days <= 5) return 'soon'; if (days <= 10) return 'watch'; return 'safe'; }
  urgencyText(product: Product) { const days = this.daysUntil(product.expiration_date); if (days < 0) return `Caducó hace ${Math.abs(days)} d`; if (days === 0) return 'Caduca hoy'; if (days === 1) return 'Caduca mañana'; return `Caduca en ${days} días`; }
  async enableNotifications() { if (!('Notification' in window)) { this.message.set('Este navegador no admite notificaciones.'); return; } const permission = await Notification.requestPermission(); if (permission !== 'granted') { this.message.set('Necesitas aceptar los permisos para recibir avisos.'); return; } if (!this.auth.vapidPublicKey() || !this.connected()) { this.message.set('Avisos activados en el navegador. Añade la clave VAPID para recibir avisos aunque la app esté cerrada.'); return; } const registration = await navigator.serviceWorker.ready; const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: this.base64ToUint8Array(this.auth.vapidPublicKey()) }); await this.api.subscribe(subscription.toJSON()); this.message.set('Avisos activados. Te recordaremos los productos a 10, 5, 1 y 0 días.'); }
  async signIn() { const email = this.loginEmail().trim(); const password = this.loginPassword(); if (email.length > 254 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) { this.loginError.set('Introduce un correo electrónico válido.'); return; } if (!password) { this.loginError.set('Introduce tu contraseña.'); return; } this.loginLoading.set(true); this.loginError.set(''); try { await this.auth.initialize(); if (!this.auth.configured()) throw new Error('Supabase no está configurado.'); await this.auth.signInWithPassword(email, password); } catch (error) { const code = (error as { code?: string }).code; if (code === 'email_not_confirmed') this.loginError.set('Este correo aún no está confirmado. Confírmalo desde Supabase > Authentication > Users.'); else if (code === 'email_provider_disabled') this.loginError.set('El acceso por correo y contraseña está desactivado en Supabase.'); else if (!this.auth.configured()) this.loginError.set('Falta la configuración pública de Supabase. Reinicia la web e inténtalo de nuevo.'); else this.loginError.set('Correo o contraseña incorrectos, o el acceso no está disponible.'); } finally { this.loginPassword.set(''); this.passwordVisible.set(false); this.loginLoading.set(false); } }
  openLogoutDialog() { this.logoutDialogOpen.set(true); window.setTimeout(() => document.getElementById('logout-cancel')?.focus()); }
  closeLogoutDialog() { if (this.logoutLoading()) return; this.logoutDialogOpen.set(false); window.setTimeout(() => document.getElementById('logout-trigger')?.focus()); }
  @HostListener('document:keydown.escape') onEscape() { if (this.captureDialogOpen()) this.closeCaptureDialog(); else this.closeLogoutDialog(); }
  async logout() { this.logoutLoading.set(true); try { await this.auth.signOut(); this.logoutDialogOpen.set(false); } catch { this.message.set('No se ha podido cerrar la sesión. Inténtalo de nuevo.'); } finally { this.logoutLoading.set(false); } }
  private resetCapture() { this.selectedFile.set(null); this.previewUrl.set(null); this.extracted.set(null); this.replacingId.set(null); } private base64ToUint8Array(value: string) { const raw = atob(value.replace(/-/g,'+').replace(/_/g,'/')); return Uint8Array.from(raw, c => c.charCodeAt(0)); }
}
